export const people = [
  {
    id: "1",
    name: "Luke Skywalker",
    email: "172",
    gender: "male",
    status: "blond",
  },
  {
    id: "2",
    name: "C-3PO",
    email: "167",
    gender: "no gender",
    status: "n/a",
  },
  {
    id: "3",
    name: "R2-D2",
    email: "96",
    gender: "no gender",
    status: "n/a",
  },
  {
    id: "4",
    name: "Darth Vader",
    email: "202",
    gender: "male6",
    status: "none",
  },
  {
    id: "5",
    name: "Leia Organa",
    email: "150",
    gender: "female",
    status: "brown",
  },
  {
    id: "6",
    name: "Owen Lars",
    email: "178",
    gender: "male",
    status: "brown, grey",
  },
  {
    id: "7",
    name: "Beru Whitesun lars",
    email: "165",
    gender: "female",
    status: "brown",
  },
  {
    id: "8",
    name: "R5-D4",
    email: "97",
    gender: "no gender",
    status: "n/a",
  },
  {
    id: "9",
    name: "Padmé Amidala ",
    email: "183",
    gender: "female",
    status: "black",
  },
  {
    id: "10",
    name: "Obi-Wan Kenobi",
    email: "182",
    gender: "male",
    status: "auburn, white",
  },
];
